query GetStudioFilmography(
  $id: Int,
  $search: String,
  $page: Int,
  $perPage: Int,
  $sort: [MediaSort],
  $isMain: Boolean = true
) {
  Studio(id: $id, search: $search) {
    id
    name
    isAnimationStudio
    siteUrl
    favourites
    media(page: $page, perPage: $perPage, sort: $sort, isMain: $isMain) {
      pageInfo {
        total
        currentPage
        lastPage
        hasNextPage
      }
      nodes {
        id
        idMal
        title {
          romaji
          english
        }
        coverImage {
          extraLarge
          large
          medium
        }
        format
        type
        status
        episodes
        chapters
        averageScore
        popularity
        genres
        startDate {
          year
        }
      }
    }
  }
}
